apiVersion: v1
kind: Service
metadata:
  name: pythonapp
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 32592
  selector:
    app: python

